services:
  frontend:
    build:
      context: ./requirements/frontend
      dockerfile: Dockerfile
    container_name: ${CONTAINER_FE}
    image: ${CONTAINER_FE}
    restart: unless-stopped
    ports:
      - "${FE_PORT}:${FE_PORT}"
    environment:
      - FE_PORT=${FE_PORT}
    volumes:
      - ${VOLUME_FE_HOST}:${VOLUME_FE_CONTAINER}
      - ${VOLUME_FE_CONTAINER}/node_modules
